// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		// Gets the number of times to run from the user.
		int noOfTimes = Integer.parseInt(args[0]);

		// Declares variables to store No. of times > 0.5, No. of times <= 0.5.
		int lowerEnd = 0;
		int upperEnd = 0;

		// Generates the random numbers.
		for (int i = 0; i <= noOfTimes; i++) {
			double j = Math.random();
			if (j > 0.5) {
				upperEnd++;
			} else {lowerEnd++;}
		}

		// Calculates the ratios.
		double ratio = (double) upperEnd / lowerEnd;

		// Prints results.
		if (lowerEnd != 0) {
			System.out.println("> 0.5:  " + upperEnd + " times");
			System.out.println("<= 0.5: " + lowerEnd + " times");
			System.out.println("Ratio:  " + ratio);
		} else {
			System.out.println("> 0.5:  " + upperEnd + " times");
			System.out.println("<= 0.5: " + lowerEnd + " times");
		}
	}
}
